name: presubmit

on:
  pull_request:
    branches:
      - master

jobs:
  presubmit:
    name: Presubmit Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: 'Exporting cargo bin to PATH'    
        run: echo "PATH=$PATH:/home/runner/.cargo/bin/" >> $GITHUB_ENV
      - name: Setup rust related environment variables
        shell: bash
        run: |
            rm -rf ~/.cargo/registry
            cargo version
            cargo install mdbook-llms-txt-tools 

      - run: mdbook build
