name: presubmit

on:
  pull_request:
    branches:
      - main

jobs:
  presubmit:
    name: Presubmit Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup rust related environment variables
        shell: bash
        run: |
            cargo version

      - name: Setup mdBook
        uses: baptiste0928/cargo-install@v3
        with:
            crate: mdbook-llms-txt-tools
      - run: mdbook build
